# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ef4471bbc92cd38dffb5074f08357f3e394eecfdfcde5e03ae559bc2ac35fb6e6f922108ab4489eb80957d2e8ee11a273635d0a34feddbfcd34908490be654ed

test:
  secret_key_base: 49f67b20af5f368a48618a9fc817386e17dd91cbe77cd080247c8d6ac9be75c54a70b7a276a73d6cfae0339811acde2da80dca4cfb6a2453de1bbbfe280b716d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
